services:
  api:
    build: .
    environment:
      COGNITO_REGION: ${COGNITO_REGION}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
      TOKEN_KEY_URL: ${TOKEN_KEY_URL}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb:10.5
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
